name: start.yml

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2

      - name: Install Tor and Proxychains4 for Anonymized Requests
        run: |
          sudo apt-get update
          sudo apt-get install -y tor proxychains4

      - name: Configure Tor with Control Port and Password
        run: |
          echo "ControlPort 9051" | sudo tee -a /etc/tor/torrc
          echo "HashedControlPassword 16:F6619F3AC6F73A1C603AF765CD9850B6D0FC6F0E2E56FA0A32A255B191" | sudo tee -a /etc/tor/torrc
          echo "CookieAuthentication 0" | sudo tee -a /etc/tor/torrc

      - name: Start Tor Service
        run: sudo service tor start

      - name: Set Up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Virtual Framebuffer for Headless Chrome
        run: |
          Xvfb :99 -ac &
          export DISPLAY=:99

      - name: Execute start.py for Manual Trigger
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: python start.py
